---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Gather NTP info about all ESXi Host in the given Cluster
    community.vmware.vmware_host_ntp_info:
      validate_certs: False
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      cluster_name: '{{ cluster_name }}'
    delegate_to: localhost
    register: cluster_host_ntp
  - debug:
      msg: "{{ cluster_host_ntp }}"
